name: Expo CI CD

on:
  push :
    branches : [main]

jobs:
  Build-for-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 5.x
          expo-username: sanchit_sd
          expo-password: 123sandwi123@saM
#       - name: Install deps
#         run: yarn install
#       - name: Run tests
#         run: |
#           yarn
#           yarn test
#         env:
#           CI: true
#       - name: Build Android APK Bundle
#         run: expo build:android
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ../Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tinder:latest
