name: Expo CI CD

on:
  push :
    branches : [main]

jobs:
  Build-for-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 5.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
      - name: Install deps
        run: yarn install
      - name: Run tests
        run: |
          yarn
          yarn test
        env:
          CI: true
      - name: Format using Prettifier
        run: npm run prettier-format
      - name: Lint
        run: npm run lint
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sanchitdwivedi/tinder
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Android APK Bundle
        run: expo build:android
